# Intro

Helper functions for FCC exercises.

In [31]:
test_array = [ '"From a Buick 8","King, Stephen",2002,"Shelf K7"',
  '"The Shining","King, Stephen",1977,"Shelf K1"',
  '"The Stand","King, Stephen",1978,"Shelf K2"',
  '"It","King, Stephen",1986,"Shelf K3"',
  '"Misery","King, Stephen",1987,"Shelf K4"',
  '"Do Androids Dream of Electric Sheep?","Dick, Philip K.",1968,"Shelf D5"',
  '"I, Robot","Asimov, Isaac",1950,"Shelf A8"',
  '"Foundation","Asimov, Isaac",1951,"Shelf A9"',
  '"Dune","Herbert, Frank",1965,"Shelf H3"',
  '"Neuromancer","Gibson, William",1984,"Shelf G8"',
  '"Snow Crash","Stephenson, Neal",1992,"Shelf S6"',
  '"The Martian","Weir, Andy",2011,"Shelf W5"',
  '"Ender\'s Game","Card, Orson Scott",1985,"Shelf C2"',
  '"The Hitchhiker\'s Guide to the Galaxy","Adams, Douglas",1979,"Shelf A1"',
  '"Ready Player One","Cline, Ernest",2011,"Shelf C7"',
  '"The Dark Tower: The Gunslinger","King, Stephen",1982,"Shelf K5"',
  '"Unknown Title","Unknown",1975,"Shelf X1"',
  '"Mysterious Manuscript","Unknown Author",Unknown,"Shelf Z9"',
  '"Ancient Scroll","Anonymous",850,"Unknown"' ]
for i in test_array:
    print(i)

"From a Buick 8","King, Stephen",2002,"Shelf K7"
"The Shining","King, Stephen",1977,"Shelf K1"
"The Stand","King, Stephen",1978,"Shelf K2"
"It","King, Stephen",1986,"Shelf K3"
"Misery","King, Stephen",1987,"Shelf K4"
"Do Androids Dream of Electric Sheep?","Dick, Philip K.",1968,"Shelf D5"
"I, Robot","Asimov, Isaac",1950,"Shelf A8"
"Foundation","Asimov, Isaac",1951,"Shelf A9"
"Dune","Herbert, Frank",1965,"Shelf H3"
"Neuromancer","Gibson, William",1984,"Shelf G8"
"Snow Crash","Stephenson, Neal",1992,"Shelf S6"
"The Martian","Weir, Andy",2011,"Shelf W5"
"Ender's Game","Card, Orson Scott",1985,"Shelf C2"
"The Hitchhiker's Guide to the Galaxy","Adams, Douglas",1979,"Shelf A1"
"Ready Player One","Cline, Ernest",2011,"Shelf C7"
"The Dark Tower: The Gunslinger","King, Stephen",1982,"Shelf K5"
"Unknown Title","Unknown",1975,"Shelf X1"
"Mysterious Manuscript","Unknown Author",Unknown,"Shelf Z9"
"Ancient Scroll","Anonymous",850,"Unknown"

In [19]:
import pandas as pd

pd.read_csv('addresses.csv')

,John,Doe,120 jefferson st.,Riverside,NJ,08075
0,Jack,McGinnis,220 hobo Av.,Phila,PA,9119
1,"John ""Da Man""",Repici,120 Jefferson St.,Riverside,NJ,8075
2,Stephen,Tyler,"7452 Terrace ""At the Plaza"" road",SomeTown,SD,91234
3,NaN,Blankman,NaN,SomeTown,SD,298
4,"Joan ""the bone"", Anne",Jet,"9th, at Terrace plc",Desert City,CO,123

In [32]:
import pandas as pd

pd.read_csv('test.csv')

                          From a Buick 8      King, Stephen     2002  Shelf K7
0                            The Shining      King, Stephen     1977  Shelf K1
1                              The Stand      King, Stephen     1978  Shelf K2
2                                     It      King, Stephen     1986  Shelf K3
3                                 Misery      King, Stephen     1987  Shelf K4
4   Do Androids Dream of Electric Sheep?    Dick, Philip K.     1968  Shelf D5
5                               I, Robot      Asimov, Isaac     1950  Shelf A8
6                             Foundation      Asimov, Isaac     1951  Shelf A9
7                                   Dune     Herbert, Frank     1965  Shelf H3
8                            Neuromancer    Gibson, William     1984  Shelf G8
9                             Snow Crash   Stephenson, Neal     1992  Shelf S6
10                           The Martian         Weir, Andy     2011  Shelf W5
11                          Ender's Game  Card, Orson Scott     1985  Shelf C2
12  The Hitchhiker's Guide to the Galaxy     Adams, Douglas     1979  Shelf A1
13                      Ready Player One      Cline, Ernest     2011  Shelf C7
14        The Dark Tower: The Gunslinger      King, Stephen     1982  Shelf K5
15                         Unknown Title            Unknown     1975  Shelf X1
16                 Mysterious Manuscript     Unknown Author  Unknown  Shelf Z9
17                        Ancient Scroll          Anonymous      850   Unknown

In [31]:
import re

# Not perfect, but gets me most of the way there.
def get_java_string_concat_from_text(your_text, 
                                     variable_wrapper="sq"):
    VARIABLE_WRAPPERS = {"sq": "[]"}
    your_variable_wrapper = VARIABLE_WRAPPERS[variable_wrapper]
    # Everytime you replace a variable wrapper, you need to 
    # 1. Replace " [" with '" + " " + '
    new_text = re.sub(' \[', "' + ' ' + ", your_text)
    # 2. Replace "]" with "+ '"
    new_text = re.sub('] ', " + '", new_text)
    new_text = re.sub("]'", "", new_text)
    new_text = re.sub("].", " + '.", new_text)

    # 3. Replace "]"
    return new_text

    
# test_text = "'A big [brown] fox.'"
test_text = "'Once upon a time, there was a(n) [adjective] [noun] who loved to eat [noun2]. The [noun] lived in a [place] and had [adjective2] nostrils that blew fire when it was [verb].'"
get_java_string_concat_from_text(test_text)

"'Once upon a time, there was a(n)' + ' ' + adjective + ' ' + noun + 'who loved to eat' + ' ' + noun2 + '. The' + ' ' + noun + 'lived in a' + ' ' + place + 'and had' + ' ' + adjective2 + 'nostrils that blew fire when it was' + ' ' + verb + '.'"